### ISSUE TITLE
Safari Desktop and Mobile issues

### ISSUE THREAD

**Issue by bostinait** [hilongjw/vue-lazyload#1]
Hi, 

I'm having a couple of issues that I hope you can help with, firstly the code at the bottom of this issue is throwing an error on Safari (on MBP)

**SyntaxError: Unexpected use of reserved word 'let' in strict mode**

```javascript
img: new Set(),
    /* set the img show with it state */
    show() {
      let self = this; <- this line
```

Also get the below error on Safari mobile (iOS iPhone 6S)

**SyntaxError: Unexpected token '('. Expected a ':' following the property name 'show'.**

```javascript
img: new Set(),
    /* set the img show with it state */
    show() { <- this line
```
The same code works on Chrome on my MBP

This is in my js file

```javascript
var Vue = require('vue');
Vue.use(require('vue-resource'));
var LazyLoad = require('vue-lazyload');
Vue.use(LazyLoad, {
    error: '/assets/img/trans-1x1.png',
    loading: '/assets/img/trans-1x1.png'
});
```

Then in my html I have

    <img :height="goal.medias[0].size.height" :width="goal.medias[0].size.width" v-lazy="goal.medias[0].file_path + '/' + goal.medias[0].file_name +'?w=450'" :alt="goal.title + ' | iGerit'">

**Comment by hilongjw** [comment]
it seems like these bowser can't support let, and I have add babel compile code to es5, and because babel can't suport ES6's Set compile to ES5, I removed the set, please update vue-lazyload.
