### ISSUE TITLE
Do you want to add a lazy-loading component feature to your repository

### ISSUE THREAD

**Issue by ihaichao** [hilongjw/vue-lazyload#101]

**Comment by hilongjw** [comment]
@ihaichao sure, here is a test component [lazy-component.js](https://github.com/hilongjw/vue-lazyload/blob/master/src/lazy-component.js)

**Comment by ihaichao** [comment]
OK. It seems that the feature is still in development. May I make a contribution to it?

**Comment by hilongjw** [comment]
@ihaichao of course you can，welcome for your pr or idea

**Comment by ihaichao** [comment]
I have an idea. The elements which are not in the first screen contain a placeholder image. When scrolling the screen to somewhere which is near the element, the image loaded, then executing a method to request  data to render the element. The html is like below.

`<div class="part" v-lazy:background-image="img" v-lazy-callback="test"></div>`

I think the test method should be in the root instance and I found that I can't get the root instance.
What do you think of this idea?
By the way, I'm not really understand some of your code. Could you write some comments?
Thanks.

**Comment by hilongjw** [comment]
@ihaichao lazyloading data sounds good. it will call another directive when use `v-lazy-callback="test"`, here is what I recommend
```html
<div class="part" v-lazy:background-image="{ src: 'some_url', callback: loadNextData  }"></div>

<lazy-component @show="loadNextData"></lazy-component>
```
