### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by lohas923** [hilongjw/vue-lazyload#103]
用vue-cli 生成的项目，编译发生错误。
`in ./~/.10.0.2@vue-loader/lib/template-compiler.js?id=data-v-4b9fcf17!./~/.10.0.2@vue-loader/lib/selector.js?type=template&index=0!./src/components/Bjqview.vue template syntax error - invalid expression: v-lazy="http://hilongjw.github.io/vue-lazyload/dist/404.png"`

VUE 版本
"vue": "^2.1.0",
    "vue-lazyload": "^1.0.0-rc8",
    "vue-router": "^2.1.1",
    "vuex": "^2.0.0"

main.js 有这样
import VueLazyload from 'vue-lazyload'
Vue.use(VueLazyload)

.babelrc 是这样的
`{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime"],
  "comments": false
}`

**Comment by hilongjw** [comment]
@lohas923  
v-lazy 指令内容应该为变量 
```
<img v-lazy=" 'http://hilongjw.github.io/vue-lazyload/dist/404.png' " />
```
