### ISSUE TITLE
horizontal scrolling not load？

### ISSUE THREAD

**Issue by aiyadingya** [hilongjw/vue-lazyload#104]
I have a local area on the HTML page is a horizontal scrolling, when the picture elements from the outside of the screen scroll to the screen, the picture is not loaded, but then the vertical scroll, the picture will be loaded

**Comment by hilongjw** [comment]
@aiyadingya can you provide live demo at jsfiddle, codepen ?

**Comment by luchanan** [comment]
我也遇到这个问题，在谷歌模拟器（真机没测试），就是在左右lazyload的时候，发现加载不出图片出来，然后上下滑动才出现

**Comment by hilongjw** [comment]
@luchanan 
try the following code, declare your customer scrollable element with  ref 
```html
div ref="container">
     <!-- Customer scrollable element -->
     <img v-lazy.container ="imgUrl"/>
     <div v-lazy:background-image.container="img"></div>
</div>
```

**Comment by luchanan** [comment]
@hilongjw 其实不加也可以，但是呢左右lazyload，好像要等2,3秒才去请求图片（非网络原因），上下滚动的lazyload一下子就出来。

**Comment by sheyunsi** [comment]
自定义容器滚动，在移动端touchmove时不会触发图片加载。 在chrome上测试了一下，发现只有鼠标滑轮滚动会触发图片加载。
所以问题不在于是否可以横向滑动加载，我垂直方向这样也不能加载出来。 必须鼠标滚动一下，或者整个页面滑动一下才会触发图片加载。
