### ISSUE TITLE
Responsive Image

### ISSUE THREAD

**Issue by jzkitchen** [hilongjw/vue-lazyload#107]
As I add :srcset into img, the browser load the images automatically even the images are not on screen. I find this problem using developer tools of Chrome.

**Comment by hilongjw** [comment]
@jzkitchen I think we should avoid using `srcset` with img tag

**Comment by hilongjw** [comment]
will fix  in next version, I will use `data-srcset` instead `srcset `

**Comment by hilongjw** [comment]
[fixed in 1.0.0-rc12](https://github.com/hilongjw/vue-lazyload/releases/tag/1.0.0-rc12)
