### ISSUE TITLE
Handling of 'wheel' input event was delayed for 109 ms due to main thread being busy.

### ISSUE THREAD

**Issue by LG0012** [hilongjw/vue-lazyload#109]
http://prntscr.com/e0796e
http://prntscr.com/e079cd

I'm not sure if this is a huge problem, but yeah, i got this warning. So i don't know, maybe someone have a solution for this issue?

**Comment by hilongjw** [comment]
I think the problem is related to [Passive event listeners](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md)

**Comment by hilongjw** [comment]
@LG0012 fixed in [SupportsPassive](https://github.com/hilongjw/vue-lazyload/commit/929fa68272ff030b2e1db665060344d453c9f350)
