### ISSUE TITLE
Install as standalone script

### ISSUE THREAD

**Issue by tpalmer75** [hilongjw/vue-lazyload#112]
Hi, I'm trying to install this without import or Webpack.

I've included the JS:

`<script src="vue-lazyload.js"></script>`

and in my `app.js` I've written:

```
Vue.use(VueLazyLoad)

new Vue({
    el: '#app',
    data: {
        ...
    }
)}
```

However the browser responds with `Uncaught ReferenceError: VueLazyLoad is not defined`.

**Comment by hilongjw** [comment]
@tpalmer75 fixed in [1.0.0 rc10](https://github.com/hilongjw/vue-lazyload/commit/8b2e16c52abe1a72f279963b376d7bfb53e12a8b)
