### ISSUE TITLE
>= 0.4.3 的版本 webpack 打包出错

### ISSUE THREAD

**Issue by maskzh** [hilongjw/vue-lazyload#113]
![image](https://cloud.githubusercontent.com/assets/4187081/22675341/1090ae2e-ed20-11e6-9a68-ff2f0a783d0c.png)

**Comment by hilongjw** [comment]
@maskzh suggest upgrade to 1.0.0-rc10

```bash
npm i vue-lazyload@1.0.0-rc10 --save-dev
```

**Comment by maskzh** [comment]
OK, Thanks
