### ISSUE TITLE
`loaded` not called if image already in cache?

### ISSUE THREAD

**Issue by Cristy94** [hilongjw/vue-lazyload#115]
I wanted to add a callback to resize a div whenever an image is loaded (because that changes the size of the content), but the `loaded` event is not received if the image is already in cache (same src was previously loaded).

What event can I subscribe to, to be notified whenever an image is loaded regardless if it's in cache or not?

For now, to fix this issue, I add a random URL param at the end of the `src`, but this stops the browser from caching the image...

**Comment by hilongjw** [comment]
@Cristy94 fixed in rc12
