### ISSUE TITLE
two scrollbar then in  lazy load sometimes image is not coming 

### ISSUE THREAD

**Issue by jigar-halani** [hilongjw/vue-lazyload#117]
I have two scrollbar in page one is browser and one is product image scrollbar when image is loading it shows me loading properly for the image which is visible at that time but when I move the scrollbar to the last position that time it show loading in the image until I not leave scrollbar and move back to that scrollbar.

please check and let me know if there is any solution.

**Comment by hilongjw** [comment]
@jigar-halani  Can you provide online repo or demo page?
