### ISSUE TITLE
Memory leak when creating/removing lazy components

### ISSUE THREAD

**Issue by Cristy94** [hilongjw/vue-lazyload#118]
I noticed that my app had a pretty big memory leak when elements where created/deleted. I narrowed down the issue to be with `vue-lazyload` event listeners.

It seems that the listeners are not removed when the HTML elemnt (lazy-component) is removed. Also, is the listener be removed after the load is complete? If yes, then it means that this memory leak only occurs when the element is removed before it was loaded.

**Comment by hilongjw** [comment]
[fixed in 1.0.0-rc12](https://github.com/hilongjw/vue-lazyload/releases/tag/1.0.0-rc12)
