### ISSUE TITLE
重复加载图片

### ISSUE THREAD

**Issue by wangwei123** [hilongjw/vue-lazyload#119]
在监控到scroll事件后，已经显示的图片会重新刷新，页面会出现闪动

**Comment by hilongjw** [comment]
Can you provide online repo or demo page?

**Comment by ximan** [comment]
"vue-lazyload": "^1.2.1",同样问题
我的需求是某一个div滚动，里面懒加载。并且还要监听这个div滚动，然后做返回顶部。
<div class="channel" ref="container">
<img v-lazy.container="item.image">
只要我在mounted方法里增加监听.channel的scroll事件
document.querySelector('.channel').addEventListener('scroll',()=>{})
页面上之前正常的图片懒加载，页面一滚动，图片src就会不断重复继续做请求。

希望解决

**Comment by ximan** [comment]
我上面的问题已经解决。
因为我需要一个滑动一定距离显示返回顶部按钮，在scroll事件里加了修改当前vue页面date属性isBackUpShow:false。一旦在scroll里修改isBackUpShow，恰巧<img v-lazy.container="change(item.image)">这里的原始图片需要通过change方法修改图片尺寸，修改图片又会触发cdn图片打乱url，所以每次isBackUpShow改变，change就会自动执行，图片就会更换url。
解决办法是，把item.image这个数组里的图片，在computed先处理好。或者是在store里先处理好，而不是在<img>标签的方法里去处理。

这个不是本插件的问题，误会一场。
