### ISSUE TITLE
为什么会引入两次呢？

### ISSUE THREAD

**Issue by docikaci** [hilongjw/vue-lazyload#122]
引入方式：
![image](https://cloud.githubusercontent.com/assets/7788102/23456700/845852da-feaf-11e6-873d-2f64d2005c73.png)

打包之后的文件？
![image](https://cloud.githubusercontent.com/assets/7788102/23456692/77e830ec-feaf-11e6-96db-0edbabc9085a.png)

**Comment by hilongjw** [comment]
可能你是依赖的某一个库依赖了老版本得 vue lazyload，请尝试排查一下（mint-ui?）

**Comment by docikaci** [comment]
膜拜，真有用到mint-ui? 那怎么处理恰当呢？ 引入一个

**Comment by hilongjw** [comment]
使用 
```bash
npm remove vue-lazyload

npm i vue-lazyload --save
```

这样就是引用同样版本的vue lazyload，会被webpack自动去重
