### ISSUE TITLE
某个data改变会导致所有的lazyload的图片重新加载一遍是什么鬼

### ISSUE THREAD

**Issue by xuejianrong** [hilongjw/vue-lazyload#123]
之前rc10的时候就有这个问，然后安装了rc9就好了，现在vue2.2版本使用rc9会报错

**Comment by xuejianrong** [comment]
我看到的现象应该是：凡是有数据改变，然后所有延迟加载的图片都是先src变成空，然后再给上我设置的src

**Comment by hilongjw** [comment]
@xuejianrong 目前最新版是 1.0.0 rc12， 可以提供一个在线运行的demo吗？

**Comment by hilongjw** [comment]
@xuejianrong fixed at version 1.0.0
