### ISSUE TITLE
vue2.x时，数据改变，图片没有改变

### ISSUE THREAD

**Issue by fengshenhai-0727** [hilongjw/vue-lazyload#124]
需要加配置吗？

**Comment by hilongjw** [comment]
Can you provide online repo or demo page?

**Comment by JoweiBlog** [comment]
I used Swiper to make a Banner component, Asynchronous access to image data,  but img is not set;
only i set a sign <img v-lazy="xxx"/> at the start,  done;   ...

**Comment by fengshenhai-0727** [comment]
var addListener = function addListener(el, binding, vnode) {
            if (el.getAttribute('lazy') === 'loaded' && binding.oldValue === binding.value) return;
...
当切换不同城市时，相应的景点图片也要改变，之前加载过的图片lazy=loaded的，再次加载直接return了，加了binding.oldValue === binding.value解决了

**Comment by hilongjw** [comment]
fixed at v1.0.1
