### ISSUE TITLE
Tagging prereleases incorrectly

### ISSUE THREAD

**Issue by marcelombc** [hilongjw/vue-lazyload#127]
You are not following the [semver spec for prereleases](https://docs.npmjs.com/misc/semver#prerelease-tags).
This leads to `yarn` install the version `1.0.0-rc9` instead of `1.0.0-rc12`, because, following the spec, `1.0.0-rc9` is the most recent version.

**Comment by hilongjw** [comment]
@marcelombc fixed, new version is `1.0.0`

**Comment by marcelombc** [comment]
@hilongjw, the latest version is still 1.0.0-rc12.  Are you going to release version 1.0.0 in the near future?

**Comment by hilongjw** [comment]
@marcelombc the lastest version is  [1.0.1](https://www.npmjs.com/package/vue-lazyload)
