### ISSUE TITLE
no versions available

### ISSUE THREAD

**Issue by winkying** [hilongjw/vue-lazyload#128]
1.0.0rc12版本部分img标签上绑定loading和status状态失败，并没有初始化img的src默认值和状态，貌似绑定的$once事件也没有调用。。
0.9.x版本的global.install根本没有暴露VueLazyload对象，也没有绑定到window上，不能使用Vue.use(VueLazyload)
0.8.x版本的require不能直接在浏览器中使用

**Comment by hilongjw** [comment]
可以提供一个在线的demo吗，是从低版本一逐渐添加的这些功能，目前最新版为1.0.0rc12

**Comment by winkying** [comment]
http://m.laiyifen.com/view/h5/30.html
这个是线上的用的是rc12，script引入方式，可以看到上面的图片链接是：<img width="100%" src="http://images.laiyifen.com/laiyifen/2013/72274/72274_01_l.jpg?v=1.0" lazy="loaded">

然而下面的是这样：<img width="100%">

没有默认src值，也没有lazy状态

用了0.8.x版本 import也这样，后来我这样用了：window.VueLazyload = window.install; 能正常work  :(>

**Comment by hilongjw** [comment]
@winkying 已经在1.0.0 修复了这个 ```<img width="100%">``` 问题

**Comment by rockybean** [comment]
话说为什么把 class cov 给去掉了……

**Comment by hilongjw** [comment]
@rockybean `cov` 是之前用于测试的一个 class，没有特殊意义，所以在1.0.0之后被删除，你可以自由定制的lazy-component属性。
```html
<lazy-component @show="handler" class="your-class-name">
  ...
</lazy-component>
```

**Comment by rockybean** [comment]
明白，之前基于这个设定的一些样式，然后升级就跪了……
