### ISSUE TITLE
Issue when loading the images over fixed height div with overflow

### ISSUE THREAD

**Issue by malaymehta** [hilongjw/vue-lazyload#13]
Hello @hilongjw,

I have been using this package and found that if the images container have been restricted toa  fixed height and allowing overflow vertically, the lazyloading doesn't seem to work.

Do you guys have any suggestions. Let me know if you need anything else.

**Comment by Leopoldthecoder** [comment]
@malaymehta Hi I'm having the same problem and have committed a pr #14 . Perhaps you can try fixing the code according to the pr and leave me a feedback here regarding if it works for you. Thanks!

**Comment by hilongjw** [comment]
hi, @malaymehta , @Leopoldthecoder  helped me fix the problem

**Comment by malaymehta** [comment]
Hey, I reinstalled the package and I see the code changes in there, but it doesn't work for me. I opened an another issue for the same.
