### ISSUE TITLE
When I use lazyload component, the handler executed continually.

### ISSUE THREAD

**Issue by ihaichao** [hilongjw/vue-lazyload#130]
I have no idea what the problem is.
Could you write a demo which using lazyload component?

**Comment by hilongjw** [comment]
You can check [here](https://github.com/hilongjw/vue-lazyload-run/blob/master/src/components/list-c.vue)

**Comment by ihaichao** [comment]
I checked that repository, the issue still exists.

**Comment by hilongjw** [comment]
@ihaichao fixed it in v1.0.1

**Comment by hilongjw** [comment]
I forgot set `state.loaded = true` after lazyload component showed.
