### ISSUE TITLE
Images loaded are loaded again on scroll

### ISSUE THREAD

**Issue by kyoukhana** [hilongjw/vue-lazyload#133]
I noticed something when the image are loaded and if i scroll again on the iPhone the reload again.  Is there something i need to change in the code maybe set from scroll to touch move?

**Comment by GeunhoKim** [comment]
+1
same issue on mobile safari.

**Comment by hilongjw** [comment]
@kyoukhana @GeunhoKim fixed in v1.0.2 [commit](https://github.com/hilongjw/vue-lazyload/commit/cd1032ec08fa974d877fb1865f6060664f3c0aa5)

**Comment by mohamedelhosseiny** [comment]
Not fixed, issue is still present on Iphone :/
