### ISSUE TITLE
Problem with overflow-scrolling: touch in Safari

### ISSUE THREAD

**Issue by cnzh2992** [hilongjw/vue-lazyload#134]
I have multiple horizontally scrollable elements in my page. (something like app store)
Each scrollable element contain a list of image elements with `v-lazy` directive.
`overflow-scrolling: touch` is set on each scrollable element to enable inertial scrolling.

the problem is **images scrolled in due to inertia** are not loaded.

So I debug the code and found `scroll` event is only attached to the first scrollable element and window.
The following scrollable elements can still lazyload the image seems because `touchmove` event is triggered on `window`.

Here is my config:
```
    Vue.use(VueLazyload, {
      preload: 1.3,
      attempt: 1,
      listenerEvents: ['scroll', 'resize']
    })
```

Do I miss something? Thanks!

**Comment by hilongjw** [comment]
try 
``` javascript
 Vue.use(VueLazyload, {
      preload: 1.3,
      attempt: 1,
      listenerEvents: ['scroll', 'resize', 'touchend', 'touchmove']
    })
```

**Comment by hilongjw** [comment]
```html
 <div ref="container">
     <!-- Customer scrollable element -->
     <img v-lazy.container ="imgUrl"/>
     <div v-lazy:background-image.container="img"></div>
</div>
```

**Comment by cnzh2992** [comment]
It seems that I'm not using the latest version... Thanks for the reply!
