### ISSUE TITLE
data-srcset with direct image links

### ISSUE THREAD

**Issue by ymnj** [hilongjw/vue-lazyload#136]
Running into an issue where :data-srcset does not serve the correct size to v-lazy. 
```
<img v-lazy="`http://some-site.com/photos/image.jpg`"
 data-srcset="http://some-site.com/photos/image.jpg 1344w, 
               http://some-site.com/photos/image.jpg 926w, 
               http://some-site.com/photos/image.jpg 450w" 
sizes="(min-width: 926px) 1344w, (min-width: 451px) 926w, (max-width: 450px) 450w" 
lazy="loading"> 
```
In this instance, the browser will try to make a request for a non existing image on the local server resulting in a 404.

GET http://localhost:8080/photos/image.jpg 404 (Not Found)

Upon further testing, if "data-" is removed and only srcset is used. On page load, the page will request all the images in the correct size. Then as the user scrolls down, lazy load will work by requesting the default src image. Resulting in seperate requests for each image.

**Comment by jhpmatos** [comment]
+1

**Comment by iamdubx** [comment]
I have the same issue.

**Comment by iamdubx** [comment]
Horrible package. Waste so much time for this. I already integrate it in my project a month ago, now decided to integrate responsive images, and this happening.
