### ISSUE TITLE
Can't get it to work 

### ISSUE THREAD

**Issue by zoeyinyun** [hilongjw/vue-lazyload#137]
npm run dev
会报如下的错误，vue 2.1.10 有没有人碰到过
Module build failed: ReferenceError: Unknown plugin "external-helpers" specified in "/Users/yunyin/yy/za/fiui/node_modules/vue-lazyload/.babelrc" at 0, attempted to resolve relative to "/Users/yunyin/yy/za/fiui/node_modules/vue-lazyload"

**Comment by zoeyinyun** [comment]
我的 main.js

`import Vue from 'vue';
import App from './App.vue';
import VueRouter from 'vue-router';
import Lazyload from 'vue-lazyload';

import routes from './routes.js';

Vue.use(VueRouter);

Vue.use(LazyLoad);

const router = new VueRouter({
    mode: 'hash',
    routes
});
`

**Comment by zoeyinyun** [comment]
main.js
```
import Vue from 'vue';
import App from './App.vue';
import VueRouter from 'vue-router';
import Lazyload from 'vue-lazyload';

import routes from './routes.js';

Vue.use(VueRouter);

Vue.use(LazyLoad);

const router = new VueRouter({
    mode: 'hash',
    routes
});

```

**Comment by HoldSkill** [comment]
请问什么原因呢？

**Comment by oulaly** [comment]
#233 

`{
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
}`

**exclude: /node_modules/**
