### ISSUE TITLE
Flash of image when refresh the page.

### ISSUE THREAD

**Issue by kodekrendel** [hilongjw/vue-lazyload#140]
When I refresh the page sometimes I see a flash of rendered picture on top of the page. Can I get rid of this glitch?

**Comment by hilongjw** [comment]
try use fade animation with css3 or do not use lazy load with first screen of page.
```
img[lazy=loaded] {
    animation-duration: 1s;
    animation-fill-mode: both;
    animation-name: fadeIn;
}
```

**Comment by kodekrendel** [comment]
@hilongjw thanks! fade animation seems to fixed the problem. I love vue-lazyload already :+1:

**Comment by kodekrendel** [comment]
Nah, still have the flash

**Comment by kodekrendel** [comment]
Again, my fault. 

Flash appers only in development mode (I am using Nuxt). In Production everything ok!
Thanks again @hilongjw
