### ISSUE TITLE
Lazyload doesn't work properly on initial site load

### ISSUE THREAD

**Issue by kodekrendel** [hilongjw/vue-lazyload#142]
Here's my example - http://many-winter.surge.sh/

If you go to that link, then go to Page Two, you'll see that all 4 image already loaded on the page. But if you refresh that Page Two, then Lazyload will work properly, and loading images one by one. 

How to fix it?
I am using Nuxt.

**Comment by kodekrendel** [comment]
Really appreciate any help, please.

```
<template>
  <section>
    <div ref="container">
     <img v-lazy="imgUrl"/>
     <div v-lazy:background-image="imgUrl"></div>
    </div>
    <div ref="container">
     <img v-lazy="imgUrl"/>
     <div v-lazy:background-image="imgUrl"></div>
    </div>
    <div ref="container">
     <img v-lazy="imgUrl"/>
     <div v-lazy:background-image="imgUrl"></div>
    </div>
    <div ref="container">
     <img v-lazy="imgUrl"/>
     <div v-lazy:background-image="imgUrl"></div>
    </div>

  </section>
</template>

<script>
import Vue from 'vue'

if (process.browser) {
  const VueLazyload = require('vue-lazyload')
  Vue.use(VueLazyload, {
    preLoad: 1,
    listenEvents: [ 'scroll' ],
    attempt: 1
  })
}

export default {
  data () {
    return {
      imgObj: {
        src: 'https://cdn-images-1.medium.com/max/1000/1*27_54ufzBoYXilrq_a6ChA.jpeg'
      },
      imgUrl: 'https://cdn-images-1.medium.com/max/1000/1*27_54ufzBoYXilrq_a6ChA.jpeg'
    }
  }
}
</script>

<style lang="scss"scoped>

img[lazy=loaded] {
  -webkit-animation-duration: 2s;
  animation-duration: 2s;
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
  -webkit-animation-name: fadeIn;
  animation-name: fadeIn;
}
@keyframes fadeIn {
  from {
    opacity: 0;
  }

  to {
    opacity: 1;
  }
}
</style>

```

**Comment by hilongjw** [comment]
@kodekrendel, I tested both cases and looked like there is no problem. I suggest you try multiple different image src.

**Comment by kodekrendel** [comment]
@hilongjw there are 100% problem!

1. Go to http://many-winter.surge.sh/
2. Then go to Page Two (not mention to opacity animation, because it apply to ALL images, they are NOT lazy load). You will see that all images are on the page already (they suposse to load one by one when scroll).
3. But if you then refresh the Page Two, then everything willl work fine. Images will be load one by one.

**Comment by hilongjw** [comment]
try init vue-lazyload with nuxt configuration-plugins [https://nuxtjs.org/api/configuration-plugins](https://nuxtjs.org/api/configuration-plugins)

**Comment by kodekrendel** [comment]
@hilongjw fixed by adding height. :sob:
