### ISSUE TITLE
关于filter一些问题

### ISSUE THREAD

**Issue by cjz9032** [hilongjw/vue-lazyload#145]
1. filter文档中写someProcess,但是代码里写的是customer?

2. webp其实也是customer,加了一层support detection.那么以后扩展会有webpa,webpb就显得比较奇怪了.所以我会选择直接都在customer写.

3. 另外现在的customer是以**el.attr**存在的(或者说defaultFilter无需attr).
所以我尝试使用vue filter写过: `v.lazy="item.image | toSize('120','120')"`不起作用.是因为vue@2.0不再支持这种写法了吗?

**Comment by hilongjw** [comment]
在 vue-lazyload 中 filter 并不是 vue 中的 filter 的概念，vue-lazyload 中的 filter 是在初始化指令时提供一个全局统一的 filter 处理图片相关参数的方法

```javascript
Vue.use(VueLazyload, {
    preLoad: 1.3,
    lazyComponent: true,
    error: 'dist/404.png',
    loading: 'dist/loading-spin.svg',
    listenEvents: ['scroll'],
    filter: {
        progressive (listener, options) {
            const isCDN = /qiniudn.com/
            if (isCDN.test(listener.src)) {
                listener.el.setAttribute('lazy-progressive', 'true')
                listener.loading = listener.src + '?imageView2/1/w/10/h/10'
            }
        },
        webp (listener, options) {
            if (!options.supportWebp) return
            const isCDN = /qiniudn.com/
            if (isCDN.test(listener.src)) {
                listener.src += '?imageView2/2/format/webp'
            }
        }
    }
})
```

**Comment by cjz9032** [comment]
其他不说,如果我要写一个过滤器怎么写呢

**Comment by hilongjw** [comment]
上面 progressive 和 webp 都是filter啊

**Comment by cjz9032** [comment]
| toSize('120','120') 这样的

**Comment by hilongjw** [comment]
现在 Vue (2.33) 是不支持指令 v-xxx="value | filter" 的

**Comment by cjz9032** [comment]
对..所以我才说,需要一个自定义的filter

**Comment by caokunyu** [comment]
@hilongjw 
filter 在 ios 设备上 替换 路径 失败

**Comment by oo10** [comment]
@cjz9032 最后实现了吗? 类似 v-xxx="value | filter"  的
