### ISSUE TITLE
how to make sure  "loader.gif"  load earlier than other imgs

### ISSUE THREAD

**Issue by percy507** [hilongjw/vue-lazyload#151]
@hilongjw 

Hello , i am developing a Vue.js project recently.

And i have used this awesome Vue plugin. 

But i find some problem.

**Every time i enter the main page, some pictures will load earlier than the "loader.gif" picture sometimes, so the page may seems not load graceful as expectant.**

**I wonder if is there a way to make sure "loader.gif" load first at every time.**

**Comment by hilongjw** [comment]
I'll fix it later in 1.0.4
