### ISSUE TITLE
enhance events in element

### ISSUE THREAD

**Issue by eugenioclrc** [hilongjw/vue-lazyload#155]
Just a little examplo of something that would be really cool to have;

`<img v-lazy="img" @error="errorHandler" />`

**Comment by hilongjw** [comment]
@eugenioclrc Hi, This feature has been supported in 1.0.5

```javascript
Vue.use(VueLazyload, {
    dispatchEvent: true
})
```

**Comment by eugenioclrc** [comment]
Great!
Is there a reason for having the distpachEvent prop in false by default?

I was hacking a litle bit my code;
```
mounted() {
    this.$Lazyload.$on('error', (evt) => {
      this.$nextTick(() => {
        this.errorLoadingMyImage = evt.el === this.$refs.myImage;
      });
    });
  },
```
With the event my code will be cleaner, thanks and greate work!

**Comment by hilongjw** [comment]
At present, this feature's demand is relatively low frequency, I would like to default to false will be better.
