### ISSUE TITLE
Cannot read property 'offsetTop' of null

### ISSUE THREAD

**Issue by laoxubuer** [hilongjw/vue-lazyload#17]
error和loading都设置了，但还是报错了

**Comment by Gouvi** [comment]
I am also receiving this error: Cannot read property 'offsetTop' of null.
vue-lazyload.es5.js #127

**Comment by ZhaZhengRefn** [comment]
update: function update(newValue, oldValue) {
            var _this3 = this;

            this.el.setAttribute('lazy', 'loading');
            if (!this.arg) {
                this.el.setAttribute('src', init.loading);
            } else {
                this.el.setAttribute('style', this.arg + ': url(' + init.loading + ')');
            }
            var parentEl = null;
            this.vm.$nextTick(function () {

                var timer = setInterval(function(){
                    if(_this3.el){
                        if (document.getElementById(Object.keys(_this3.modifiers)[0])) {
                            parentEl = document.getElementById(Object.keys(_this3.modifiers)[0]);
                        }
                        var pos = getPosition(_this3.el);
                        listeners.push({
                            bindType: _this3.arg,
                            try: 0,
                            parentEl: parentEl,
                            el: _this3.el,
                            src: newValue,
                            y: pos.y
                        });
                        lazyLoadHandler();
                        clearInterval(timer);
                    }
                },1000)
                
            });
        },

**Comment by MillerRen** [comment]
webpack hot update 问题，刷新下就好了

**Comment by hilongjw** [comment]
I have used other methods to achieve at 0.6.0 version
