### ISSUE TITLE
Uncaught ReferenceError: babelHelpers is not defined

### ISSUE THREAD

**Issue by chenchao2016** [hilongjw/vue-lazyload#170]
vue-lazyload.js 的babelrc配置里面添加了 babelHelpers  这个插件，然后运行的时候报错了。

详情： Uncaught ReferenceError: babelHelpers is not defined      vue-lazyload.js?810d:6

**Comment by hilongjw** [comment]
在 webpack babel loader 的配置中不应该编译node_modules中的 vue-lazyload
