### ISSUE TITLE
Files for a browser

### ISSUE THREAD

**Issue by extend1994** [hilongjw/vue-lazyload#177]
Hi I am a member of CDNJS and recently in charge of adding this library according to https://github.com/cdnjs/cdnjs/issues/11565. I am not so sure which files we need for the direct uses in a browser, which means that we could insert one line `<script src="...vue-lazyload.js"></script>` and use this library (or more than one line if needed). Could you please help me confirm the following issues?
1. We need vue-lazyload.js in v1.0.0 ~ v1.0.6 on npm.
2. We need vue-lazyload.es5.js in v0.1.5 ~ v0.9.5 on npm
3. We can not directly use vue-lazyload.js in v0.1.0 ~ v0.9.5 and vue-lazyload-next.js in v0.5.0 on npm in a browser

You could see the process of adding the library by https://github.com/cdnjs/cdnjs/pull/11617.
Thank you!

**Comment by hilongjw** [comment]
Hi @extend1994 , In the early version is not umd packaging, does not support direct uses in a browser, v1.0.0 after the support it，vue-lazyload.js

**Comment by extend1994** [comment]
Thank you so much!
