### ISSUE TITLE
能否支持 v-lazy="{{ data.img }}?from=x1"

### ISSUE THREAD

**Issue by iloveyo123u1** [hilongjw/vue-lazyload#18]
<img v-lazy="img"> 这种方式无法在 图片后添加参数

有时候，希望在生成的图片地址后增加参数，
如图片是 1.jpg

vue-lazyload 处理后变成了
<img src="1.jpg"> 

但我想在客户端动态的改变参数
如
<img src="1.jpg?from=123"> 

有办法吗

**Comment by hilongjw** [comment]
加一个method来处理试试
```
v-lazy="parse(data.img)"
```
```javascript
methods: {
   parse(src) {
     return src + 'xxx'
  }
}
```

**Comment by iloveyo123u1** [comment]
谢谢 可以了， 不过将来可能会支持直接拼接吗

**Comment by hilongjw** [comment]
v-lazy="xxx"，这里也是vue的作用域，应该是支持表达式的啊
```
v-lazy=" data.src + 'string' "
```
应该是没问题的，我有空测试一下吧

**Comment by iloveyo123u1** [comment]
是的 你发的那个可以用， 多谢
