### ISSUE TITLE
Is using IntersectionObserver an option?

### ISSUE THREAD

**Issue by rodneyrehm** [hilongjw/vue-lazyload#180]
First of all thank you for your efforts providing this utility!

Have you considered using the [IntersectionObserver API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API), as it has gained [support by most modern browsers](http://caniuse.com/#feat=intersectionobserver)? For older browsers and Safari the [polyfill](https://github.com/WICG/IntersectionObserver/tree/gh-pages/polyfill) may allow considerable simplification of this project, as this [simple demo](https://gist.github.com/PhilippSoehnlein/cb845575efcc1ecebc1c315eb8c68a7e) suggests.

**Comment by hilongjw** [comment]
@rodneyrehm Thanks for your suggestion, I'll try using IntersectionObserver, which may serve as an experimental option in the project.

**Comment by hilongjw** [comment]
vue lazyload is support [intersectionobserver](https://github.com/hilongjw/vue-lazyload#intersectionobserver) now.
