### ISSUE TITLE
data update not working

### ISSUE THREAD

**Issue by darkylmnx** [hilongjw/vue-lazyload#185]
when the data containing the url changes the image doesn't change.

how can i do ?

**Comment by darkylmnx** [comment]
my bad...

**Comment by BastianHofmann** [comment]
@darkylmnx can you please explain your mistake? Maybe other people running into the same issue made the same mistake :)

**Comment by darkylmnx** [comment]
@BastianHofmann yes I should have had haha. Unfortunately it was so long ago I don't remember what it was then. Maybe I didn't set a reactive data or something like that. Since I was using arrays I think over some images and created properties on the fly, and Vue doesn't like that. At least I think it was something like that.
