### ISSUE TITLE
vue-lazyload & Vue.Draggable ugly flashes

### ISSUE THREAD

**Issue by hstaniszewski** [hilongjw/vue-lazyload#187]
![bug2](https://user-images.githubusercontent.com/19909276/30564240-b03b2e1e-9cc4-11e7-9bad-8764cee7965d.gif)

**Fiddle link:** https://jsfiddle.net/sqssmhtz/231/

How can I avoid this flashing?

**Comment by hilongjw** [comment]
@hstaniszewski 

you should add  `:key="element.url"` for your list element.

```html
<div id="main">
    <div class="drag">
        <draggable :list="list" class="dragArea">
            <img class="element"
                 v-for="element in list"
                 :key="element.url"
                 v-lazy="element.url"/>
         </draggable>
     </div>
</div>
```
