### ISSUE TITLE
关于 SVG 的问题

### ISSUE THREAD

**Issue by Astaca** [hilongjw/vue-lazyload#191]
in VUE
Vue.use(VueLazyload, {
  preLoad: 1.3,
  error: '../static/images/defaultImage.jpg',
  loading: '../static/images/loading.svg',
  attempt: 3
})
当 loading 为svg文件时，PC上访问正常，微信上面SVG的动画就停止了，官方DEMO在微信也是同样的状态，我尝试在微信单独打开SVG,是有动画效果的。

**Comment by hilongjw** [comment]
The current use of svg animation is an abandoned feature, it is recommended not to use in the production environment.
