### ISSUE TITLE
Example single-file component with AJAX request

### ISSUE THREAD

**Issue by benmccann** [hilongjw/vue-lazyload#194]
Some more examples of using `lazy-component` would be very helpful for me.

I have a single-file component, which makes an AJAX request to load data and displays charts with the response data. Is there a way I can make this a a `lazy-component`?

The current example on the README has `@show="handler"`. However, when I try this `handler` doesn't seem to be called.

**Comment by hilongjw** [comment]
```html
<template>
  <lazy-component v-for="yourData in list">
    <your-component :your-props="yourData"></your-component>
  </lazy-component>
<template>

<script>
export default {
  data () {
    list: []
  },
  created () {
    this. getHistoricalData()
      .then(res => this.list = res.data)
  }
}
</script>
```

**Comment by benmccann** [comment]
Thank you very much for taking the time to respond and help. I'm afraid I'm still confused though. I need to have `props` in order to pass in parameters to the component. And if you look at the source for `getHistoricalData`, it's not possible to call `.then` on it.

**Comment by benmccann** [comment]
I've tried the code below, but `getHistoricalData` is never called. What triggers the `@show` handler?
```
<template>
  <lazy-component @show="getHistoricalData">
    <canvas v-for="symbol in symbols" :id="'chart-' + symbol.toLowerCase()" style="height:400px">loading {{symbol}}...</canvas>
  </lazy-component>
</template>
```

**Comment by benmccann** [comment]
Ok, I found the answer. It's because I need to specify `lazyComponent: true`:

```
Vue.use(VueLazyload, {
  lazyComponent: true
});
```
