### ISSUE TITLE
Fallback when JS is disabled and using prerender-spa-plugin

### ISSUE THREAD

**Issue by andresmrm** [hilongjw/vue-lazyload#198]
Hello! It took me some hours researching a solution to this, so I would like to share it here, hoping it help others. Also using the opportunity to ask if anyone else has a better idea about how to accomplish it.

### Context
I'm using `vue-lazyload` with the oficial vue webpack template, prerendering through `prerender-spa-plugin`, as recommended in the [docs](https://vuejs-templates.github.io/webpack/prerender.html).

### Problem
When the prerendered index.html file is opened in a browser without JS it will show only the "loading" image, not the real ones.

### Solution
In the components, I added an attribute to the img tags to keep the real url to the images:

    <img :true-src-url="url" v-lazy="url">

Then, in `webpack.prod.conf.js`, edited the `PrerenderSpaPlugin` config to this:

    new PrerenderSpaPlugin(
      path.join(__dirname, '../dist'),
      routes,
      {
        postProcessHtml: function (context) {
          return context.html.replace(
            /<img.* lazy="loading">/g,
            function (match) {
              var img = match.replace(/src=".*"/, '')
                  .replace('true-src-url', 'src')
                  .replace('lazy="loading"', 'lazy="loaded"')
              return `<noscript>${img}</noscript>`
            }
          )
        }
      }

This should place the img tags inside noscript tags and replace the `src` attribute so it points to the real image and not the "loading" one.

### What else I tried

- Setting the `src` attribute to the real image without moving the img tag to a noscript tag solved the problem on JS disabled browsers, but broke the lazy load on JS enabled browsers. Same result with `phantomPageSettings: {loadImages: true}` and `phantomPageViewportSize: {width: 200000, height: 800000}`.
- Adding the noscript tag in the vue components broke the lazy load, not sure why. Also, not sure if this helps with the problem, since JS disabled browsers will get 2 images (the real one and the "loading" one).

**Comment by hilongjw** [comment]
I think you can use `this.$Lazyload.ListenerQueue.map(node => node.load())`  to solve this problem

**Comment by andresmrm** [comment]
Thanks for the reply! I'm not working on that project anymore, but if I go back, I'll try to remember this and test.
Feel free to close this issue.
