### ISSUE TITLE
页面有20张图，有一定几率，后面的图一直显示loading.gif

### ISSUE THREAD

**Issue by iloveyo123u1** [hilongjw/vue-lazyload#20]
页面有20张图，
有一定几率，
后面的图一直显示loading.gif
并且，没有重新尝试请求图片

配置文件，尝试次数我写的10

**Comment by Yeahax** [comment]
me too！

**Comment by transtone** [comment]
一直这样，另外升级到 0.4.7 之后整个项目就编译不了了。

**Comment by hilongjw** [comment]
@transtone 0.4.7 es5 文件没有编译，现在已在0.5.0修复

**Comment by hilongjw** [comment]
@Yeahax @iloveyo123u1 我目前没有复现这个问题，或者升级到0.6.0版本使用

**Comment by Centaur** [comment]
0.7.0 仍有此问题，不是有一定几率的问题，手机上只要不是第一页里的图片，往上滚的全部加载不出来。桌面浏览器里调试似乎没这问题。

**Comment by hilongjw** [comment]
@Centaur 可以提供一下手机和相应浏览器版本吗，0.6之后使用 getBoundingClientRect 来获取el位置，对于现代浏览器是没兼容问题的

**Comment by Centaur** [comment]
目前在华为Mate8和iphone4s的webview中都是100%重现。
