### ISSUE TITLE
lazyload 展示第二屏的时候，并发请求图片非常慢

### ISSUE THREAD

**Issue by itbdw** [hilongjw/vue-lazyload#214]
打开首屏还可以，但是滚动到第二屏的时候，图片并发请求，非常慢。去掉 lazyload 就正常了。网络情况相同，关掉 cache

有 lazyload 的情况，会卡屏
http://7xs3k9.com1.z0.glb.clouddn.com/bug/with-vue-lazyload.MOV

关掉 lazyload 的情况，非常顺畅
http://7xs3k9.com1.z0.glb.clouddn.com/bug/without-vue-lazyload.MOV

<img width="1419" alt="wx20171219-160726 2x" src="https://user-images.githubusercontent.com/1267057/34146992-18a25ce8-e4d7-11e7-992e-190ec24d1602.png">

**Comment by itbdw** [comment]
可能是谷歌对 h2 的处理问题，瞬间全部请求同一个 connection_id ，导致异常

**Comment by ansonhorse** [comment]
@itbdw 请问这个问题有什么新进展么？

我也发现使用vue-lazyload后，图片可能会加载很慢。
图片：数量10多张，大小20KB左右
不使用vue-lazyload，全部图片基本50ms左右加载完成。
但是使用了vue-lazyload，经常会出现一些图片加载速度正常(跟上面所述差不多)，一些图片加载很慢，达到两三秒，很是奇怪！
而根据DevTools的Network观察到，加载慢的图片请求，大部分时间是消耗在Content download上面
![image](https://user-images.githubusercontent.com/7548142/40884358-ade9332c-6744-11e8-9992-999b0cede336.png)

**Comment by itbdw** [comment]
@ansonhorse 貌似chrome的问题，大概是从60以后就这样了。现在还那样

**Comment by ansonhorse** [comment]
@itbdw 这么一说，好像确实有这个感觉。不仅是图片，其他一些比如AJAX请求，有时候也是TTFB很快，但Content Download很慢，有空用其他浏览器看看。
对了，移动设备浏览器方面你有做过测试么，暂时我不太懂怎么查看移动浏览器的请求，UC开发版跟Mac好像不太来电。

**Comment by itbdw** [comment]
可以试试Charles，电脑安装这个，设置下手机代理

**Comment by ansonhorse** [comment]
@itbdw 谢谢~
