### ISSUE TITLE
Will it work with picture/source tags?

### ISSUE THREAD

**Issue by iamdubx** [hilongjw/vue-lazyload#220]
Hello. Awesome plugin, but will it work for responsive images with picture/source tags?

**Comment by iamdubx** [comment]
I tried it. It doesn't work. Please provide support for `picture` tag.

**Comment by hilongjw** [comment]
#213

**Comment by iamdubx** [comment]
@hilongjw does this mean `vue-lazyload` not support `picture`? If so, are you planning to add it?
