### ISSUE TITLE
data-srcset is not working, fix Docs

### ISSUE THREAD

**Issue by iamdubx** [hilongjw/vue-lazyload#222]
It doesn't work with `data-srcset` and `:data-srcset` but it work with `srcset` (incorrectly, by loading not necessary images). Why you have it in Docs?
This is first time I see library with 2500 stars and such Documentation.

**Comment by iamdubx** [comment]
```html
<div class="card-image lazy">
  <img v-lazy="'https://www.eurointegration.com.ua/images/doc/d/9/d940845-novi-pravyla-dlya-kovbasy.jpg'" srcset="https://www.eurointegration.com.ua/images/doc/d/9/d940845-novi-pravyla-dlya-kovbasy.jpg 600w, https://img.pravda.com/images/doc/c/0/c05e826-rada_485x299.jpg 800w" alt="aa" class="img">
</div>
```

NOT WORKING

Remove all `srcset` mention in your Docs - you doesn't support responsive images!!! I waste 5 hours of my time to this.

**Comment by adamduncan** [comment]
I found that the `data-srcset` is working as expected. At first I was having issues with the source URLs being output. The `getBestSelectionFromSrcset` method in this plugin does some pretty precise string manipulation, and if what you're passing in doesn't comply, you might be left with bogus URLs. For example, Cloudinary escape all of their [image params with commas](https://support.cloudinary.com/hc/en-us/community/posts/200788162-Using-special-characters-in-Text-overlaying-), in which case the  `getBestSelectionFromSrcset` is totally screwed. 

Here's a test case to quickly check your `data-srcset`:
https://jsbin.com/pomihezago/1/edit?html,js,console

It's a bit of an edge case, but might help someone one day.

**Comment by hilongjw** [comment]
here is getBestSelectionFromSrcset's code [https://github.com/hilongjw/vue-lazyload/blob/07103b7c3aab0dc7c256bf2601a41660960b5daa/src/util.js#L50](https://github.com/hilongjw/vue-lazyload/blob/07103b7c3aab0dc7c256bf2601a41660960b5daa/src/util.js#L50)
