### ISSUE TITLE
The use of the dispatchEvent attribute on ie11 for true to throw an error:TypeError Object doesn't support this action

### ISSUE THREAD

**Issue by GreenMashimaro** [hilongjw/vue-lazyload#225]
https://github.com/hilongjw/vue-lazyload/blob/ca056898248b76727b8d1bc5a068cfd739fbf505/src/lazy.js#L402
hi，I'm on ie11, set the dispatchEvent property to true，browser reported an error:"TypeError: 对象不支持此操作"
![image](https://user-images.githubusercontent.com/23225539/35685519-e71cbf56-07a4-11e8-95b1-fa60c3ba02e0.png)
The reason for this error is, 'While a window.CustomEvent object exists, it cannot be called as a constructor. Instead of new CustomEvent(...), you must use e = document.createEvent('CustomEvent') and then e.initCustomEvent(...)'
There's an [IE polyfill for the CustomEvent constructor at MDN](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent).

**Comment by hilongjw** [comment]
@GreenMashimaro  fixed at v1.2.0
