### ISSUE TITLE
How do I fool google pagespeed by not loading image until after crawl?

### ISSUE THREAD

**Issue by jericopulvera** [hilongjw/vue-lazyload#237]
Hi. I really want to have a high score in https://developers.google.com/speed/pagespeed/insights/.

I can achieve a high score if the images are below the viewport.

Is there an option for this?

**Comment by hilongjw** [comment]
try reduce `options.preload`?

**Comment by jericopulvera** [comment]
It does not show the image even on scroll after I set it to 0.2

I was thinking of doing this 

if(navigator.userAgent.indexOf("Speed Insights") == -1) { 
  var image = image;
} else {
  var image = null;
}

**Comment by hilongjw** [comment]
```javascript
Vue.use(vueLazy, {
    filter: {
      speedInsight (listener) {
         if(navigator.userAgent.indexOf("Speed Insights") !== -1) {
           listener.src = 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';
        }
})
```
