### ISSUE TITLE
貌似不支持ie10

### ISSUE THREAD

**Issue by huan0118** [hilongjw/vue-lazyload#246]
![image](https://user-images.githubusercontent.com/22437483/39117739-39d1b6b6-471a-11e8-8767-bceb9fc4e0d5.png)

**Comment by huan0118** [comment]
Does not seem to support the willingness of ie10 to support

**Comment by lvjiaxuan** [comment]
我今天也遇到了，官方的示例[demo](http://hilongjw.github.io/vue-lazyload/)也不行

**Comment by stevieyu** [comment]
me too

**Comment by chinesefeng** [comment]
hi ie10是不是需要增加相关的方法来支持ie10

**Comment by lerit** [comment]
我也发现了，ie11没问题，能否提供ie10的支持

**Comment by slevp** [comment]
貌似是这行`this.el.dataset.src = this.src`，dataset是HTML5的标准，IE10及以下貌似不支持（[https://caniuse.com/#search=dataset](https://caniuse.com/#search=dataset)）。
