### ISSUE TITLE
vue-lazy 如何结合富文本使用

### ISSUE THREAD

**Issue by ZooTopiaGG** [hilongjw/vue-lazyload#257]
后台返回：`<p><img src="http://a.object.gd-zht.com/2018/01/5a5f1a41ca358.jpg" style="max-width:100%;"><img src="http://a.object.gd-zhtcom/2018/01/5a5f1a452bd2c.jpg" style="font-size: 0.875rem; max-width: 100%;"><br></p>`
正则替换img的src：

`<p><img v-lazy="http://a.object.gd-zht.com/2018/01/5a5f1a41ca358.jpg" style="max-width:100%;"><img v-lazy="http://a.object.gd-zht.com/2018/01/5a5f1a452bd2c.jpg" style="font-size: 0.875rem; max-width: 100%;"><br></p>`

用v-html渲染后：
`<p><img v-lazy="http://a.object.gd-zht.com/2018/01/5a5f1a41ca358.jpg" style="max-width:100%;"><img v-lazy="http://a.object.gd-zht.com/2018/01/5a5f1a452bd2c.jpg" style="font-size: 0.875rem; max-width: 100%;"><br></p>
`
还是这个，没有实现懒加载 ，请问这种情况怎么解决

**Comment by L-Chris** [comment]
https://cn.vuejs.org/v2/api/#v-html
要注意文档，v-html的内容按普通 HTML 插入 - 不会作为 Vue 模板进行编译
解决方法：
使用后端传来的html文本，构造Vue实例并挂载在对应的dom上
例如：
`
let template = '<img v-lazy="http://www.text.com/test.jpg"/>
let instance = new Vue ({ template, el: documen.getElementById('test') }) // 指令应该要在这个实例注册
instance.$mount()
`

**Comment by htongtongx** [comment]
非常感谢 @hilongjw  方法有效
我的案例：
`<div v-lazy-container v-html="desc"></div>`

desc的值如下所示:
this.desc=`“<p><br></p><p><img data-src="https://shop.blackdora.xyz/files/1/7_21zip.jpg"></p><p><img data-src="https://shop.blackdora.xyz/files/1/5_28zip.jpg"></p><p><img data-src="https://shop.blackdora.xyz/files/1/1_36zip.jpg"></p><p><img data-src="https://shop.blackdora.xyz/files/1/6_26zip.jpg"></p><p><img data-src="https://shop.blackdora.xyz/files/1/9_11zip.jpg"></p><p><img data-src="https://shop.blackdora.xyz/files/1/7_20zip.jpg"></p><p><img data-src="https://shop.blackdora.xyz/files/1/10_9zip.jpg"></p>”`

**Comment by watsonhaw** [comment]
@htongtongx 不知道为啥，我的一直显示loading的图片状态，我也是使用的v-html，懒加载是执行了。但是现在不了加载后的图片了。

**Comment by ybroch** [comment]
> @htongtongx 不知道为啥，我的一直显示loading的图片状态，我也是使用的v-html，懒加载是执行了。但是现在不了加载后的图片了。

you should set selector as 'img'
