### ISSUE TITLE
删除列表中的一项时报错

### ISSUE THREAD

**Issue by ytudt** [hilongjw/vue-lazyload#26]
我通过v-for生成的列表，用了vue-lazyload，当我操作想删除列表中的一项时报下面的错？请问有方法解决吗？
vue.common.js:1019 [Vue warn]: Failed to resolve directive: lazy (found in component: <my-slider>)
vue-lazyload.es5.js:112 Uncaught TypeError: Cannot read property 'el' of undefined

**Comment by ytudt** [comment]
问题解决了componentWillUnmount这个函数改动 如下
for (i = 0; i < len; i++) {
            if(!listeners[i]){
                continue;
            }
            if (listeners[i].el === el) {

                listeners.splice(i, 1);
            }
        }

**Comment by hilongjw** [comment]
感谢，我会马上修复这里
