### ISSUE TITLE
Use multiple preload or default image 

### ISSUE THREAD

**Issue by amitsharma8891** [hilongjw/vue-lazyload#260]
Hi,

I am using below snippet, can anybody tell how can we use random loading images.

eg. /static/images/blankimg1.jpg, /static/images/blankimg2.jpg, /static/images/blankimg3.jpg
```
import VueLazyload from 'vue-lazyload'
Vue.use(VueLazyload, {
  preLoad: 1.3,
  error: '/static/images/error.png',
  loading: '/static/images/blankimg.jpg',
  attempt: 2
})
```

Thanks

**Comment by hilongjw** [comment]
`vue-lazy` directive support the Object parameter, you can customize any image placeholder with it. [usage](https://github.com/hilongjw/vue-lazyload#basic)
```vue
<img v-lazy="{
        src: 'http://xx.com/logo.png',
        error: 'http://xx.com/error.png',
        loading: 'http://xx.com/loading-spin.svg'
      }"/>
```
