### ISSUE TITLE
能不能提供一个加载前的钩子？

### ISSUE THREAD

**Issue by lytian** [hilongjw/vue-lazyload#266]
比如：1、图片加载中时，显示随机色块图片。
           2、图片过大时，通过七牛云的图片样式对图片进行压缩或者裁剪。

在我的APP项目中，差不多全部地方都用了vue-lazyload。一个一个的进行imgObj处理太麻烦，希望能够提供一个全局的加载前的钩子。

**Comment by hilongjw** [comment]
maybe  [image-listener-filter](https://github.com/hilongjw/vue-lazyload/#image-listener-filter) can handle this

**Comment by lytian** [comment]
filter我试了一下。感觉不是在加载图片前的操作，会有0.5秒左右的时间差来切换图片，体验不是很好

**Comment by oo10** [comment]
请问最后怎么解决的?

**Comment by oo10** [comment]
@lytian

**Comment by leo-wj910729** [comment]
@lytian 随机色块,是使用filter的时候,改变图片的背景颜色吗

**Comment by lytian** [comment]
嗯 @leo-wj910729
