### ISSUE TITLE
1.2.5 版本第一张图几乎必现处于loading状态，滚动后才 loaded

### ISSUE THREAD

**Issue by ypliypli** [hilongjw/vue-lazyload#269]
```js
Vue.use(VueLazyload, {
    preLoad: 1.3,
    attempt: 3
});
```
![image](https://user-images.githubusercontent.com/14327002/41303520-11594688-6ea0-11e8-9d5c-91380985d7eb.png)
![image](https://user-images.githubusercontent.com/14327002/41303621-53d2c412-6ea0-11e8-8c40-138767b14e79.png)

**Comment by hilongjw** [comment]
@ypliypli fixed in v1.2.6
