### ISSUE TITLE
UglifyJS error when update to new version (0.4.7)

### ISSUE THREAD

**Issue by imcvampire** [hilongjw/vue-lazyload#27]
After update to latest version (0.4.7), I meet this error `from UglifyJs SyntaxError: Unexpected token: name (last) [./~/vue-lazyload/vue-lazyload.es5.js:22,0]` when run `webpack -p`

**Comment by imcvampire** [comment]
You can review this pull request: https://github.com/hilongjw/vue-lazyload/pull/28

**Comment by hilongjw** [comment]
thanks for your issue, I forgot  compile es5 version with babel and l just fix it.

**Comment by imcvampire** [comment]
I think this issue should be closed now!
