### ISSUE TITLE
if image src is changed the new image does not replace the old one

### ISSUE THREAD

**Issue by hazaveh** [hilongjw/vue-lazyload#272]
Hi.

Apparently if the image location changes programatically while the page is fully rendered, the new image does not replace the old one. 

any way to achieve that ? I'm reading the image src off a vue data object.

Thanks in advance

**Comment by xingxiangchao** [comment]
I also encountered the same problem, data loaded from new, but the picture can not be replaced.

**Comment by hilongjw** [comment]
Use [key] (https://vuejs.org/v2/api/#key) to ensure that Vue does not try to patch/reuse elements

```javascript
<img v-lazy="img" :key="img">
```

**Comment by xingxiangchao** [comment]
It's settled. Thank you.
<img v-lazy="img" :key="img">

**Comment by hazaveh** [comment]
awesome! thanks
