### ISSUE TITLE
局部滚动的时候，突然松手这个时候依靠惯性滚动加载的图片都会有问题， 这个时候出于可视区域的图片都是loading状态。

### ISSUE THREAD

**Issue by CallMeZhang** [hilongjw/vue-lazyload#275]
感觉这个时候的scroll事件没有监听到，再次触碰或者滚动页面出于loading的图片又再次加载 。
![qq 20180629144048](https://user-images.githubusercontent.com/21018192/42077283-f5468de4-7baa-11e8-89fd-412be014c50e.png)

**Comment by 18365265404** [comment]
请问这个问题怎么解决的，急需解决，大神看到请回复
