### ISSUE TITLE
UC浏览器图片没有加载出来

### ISSUE THREAD

**Issue by wotermelon** [hilongjw/vue-lazyload#292]
```
<div v-lazy:background-image=""></div>
```

查看Element，div上面的data-src还是为loading时的base64图片

**Comment by wotermelon** [comment]
设置打印日志之后，发现是图片加载失败了，attempt设置了2次，2次都加载失败。切换UC language之后就莫名其妙可以了。

**Comment by Alex1990** [comment]
@wotermelon 你好，请问这个问题解决了吗?

**Comment by ddmy** [comment]
@wotermelon 你好，这个问题解决了吗

**Comment by Alex1990** [comment]
`observer`参数设置为`false`或者不设置就可以了。
