### ISSUE TITLE
图片lis被重新赋值后，图片src没有更新，还是原来的

### ISSUE THREAD

**Issue by zifenggao** [hilongjw/vue-lazyload#293]
在做一个图片列表的场景，包含下拉刷新逻辑，列表图片懒加载用的是vue-lazyload，图片资源的imageLists，首次进入该页面列表能正常渲染，下拉刷新重新发送请求获取数据，对imageLists进行重新赋值后，发现图片列表中img的src并没有改变，还是原来的，这是怎么回事？可以确定请求回的数据已经改变，而且其他数值、文字类的状态都已经根据请求回来的数据发生改变，就只有v-lazy的这个图片没有被重新赋值。

**Comment by bruceCzK** [comment]
#273

**Comment by zjydipingxian** [comment]
你好，你这个问题解决了？ 我也遇到了这样的问题

**Comment by Erimons-chan** [comment]
我用的swiper切换，就刷新第一屏有loading图片，活动后就直接加载完，没有滚屏加载了
