### ISSUE TITLE
在滚动条滚动的时候无法显示图片

### ISSUE THREAD

**Issue by acmeid** [hilongjw/vue-lazyload#30]
在滚动条滚动的过程中，即使滚动条已经到了指定的位置，图片占位符已经出现在window上，但是图片仍然不会加载出来，一定要在滚动条静止后才开始显示图片，我觉得这是一个可以优化的地方。

**Comment by hilongjw** [comment]
现在是使用debounce 的方式来处理的，之后我会使用throttle来处理

**Comment by acmeid** [comment]
好的。另外还有个建议：
从loading到loaded或error,切换的时候太唐突，感觉就是一个图片突然变成另外一个图片。我觉得可以加个动画渐变一下（比如透明度），这样会感觉流畅一点。期待你的优化。

**Comment by hilongjw** [comment]
loading->loaded 状态的切换可以通过css实现渐变，可以参考在线 [demo]( http://hilongjw.github.io/vue-lazyload/)

**Comment by acmeid** [comment]
好的，谢谢！

**Comment by hugzh** [comment]
preLoad: 1.3 这个配置参数应该如何理解呢？

**Comment by hilongjw** [comment]
@hugzh 是会加载屏幕外 1.3倍屏幕高度的图片，也就是预加载30%高度外的图片

**Comment by hugzh** [comment]
看了一下代码，非常赞，后期可以做一些代码优化或者加点注释什么的。

**Comment by hilongjw** [comment]
@hugzh 谢谢，有时间会加上函数的参数注释
