### ISSUE TITLE
Lazyloaded image won't update if its source is given through props

### ISSUE THREAD

**Issue by ahmatovicm** [hilongjw/vue-lazyload#312]
Changing the image source of a lazy-loaded image won't update the image if its source comes from a prop.

See the sandbox example below.

[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/942pj9rp2y)

**Comment by Daidalos117** [comment]
Same here. Any idea how to make it work? v-lazy just takes first value. It doesnt change if value changes..

**Comment by fyeeme** [comment]
some problem, src data has been updated, but image not change

**Comment by gniria** [comment]
@hilongjw

**Comment by ahmatovicm** [comment]
@fyeeme @gniria @Daidalos117 
Apparently, if you add a key attribute, the image will update. Updated the sandbox on my first comment and it does change. The only reason I know this, is because they updated the readme file.
