### ISSUE TITLE
改loading图不好使！

### ISSUE THREAD

**Issue by feawesome** [hilongjw/vue-lazyload#343]
改loading图不好使！
mainjs写这个有错吗 为啥就不生效
import VueLazyload from 'vue-lazyload'

Vue.use(VueLazyload, {
  preLoad: 1.3,
  error: 'dist/error.png',
  loading: require('./assets/images/loading.gif'),
  attempt: 1,
  // the default is ['scroll', 'wheel', 'mousewheel', 'resize', 'animationend', 'transitionend']
})

**Comment by stonefcs** [comment]
这个应该是个BUG，我也碰到这问题，只能写到页面里面去，并且只在img标签才会有效果
