### ISSUE TITLE
代码在vivo Xplay 5A的原生浏览器和自带浏览器上跑不起来。

### ISSUE THREAD

**Issue by dear-lizhihua** [hilongjw/vue-lazyload#35]
vivo Xplay5A
  Android: v5.1.1
  vivo ROM: Funtouch OS v2.5.1
  Sofeware Version: v1.12.16
  userAgent: Mozilla/5.0 (Linux; Android 5.1.1; vivo Xplay5A Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/38.0.0.0 Mobile Safari/537.36

**Comment by dear-lizhihua** [comment]
经排查是https://github.com/hilongjw/vue-lazyload/blob/master/vue-lazyload.es5.js中用了ES6的方法，导致浏览器报错。

**Comment by hilongjw** [comment]
@dear-lizhihua  感谢
