### ISSUE TITLE
能够源码调试么？

### ISSUE THREAD

**Issue by mrxu0** [hilongjw/vue-lazyload#367]

**Comment by kelvshi** [comment]
在vue-lazyload的那个包里把依赖装上 npm i
然后引进源码入口就可以了
`import VueLazyload from '../node_modules/vue-lazyload/src/index.js';`

**Comment by ywq1991** [comment]
不行啊，大佬

**Comment by dota17** [comment]
Reference： https://github.com/hilongjw/vue-lazyload-run
