### ISSUE TITLE
webpack UglifyJsPlugin 插件压缩 vue-lazyload 报错

### ISSUE THREAD

**Issue by GangRock** [hilongjw/vue-lazyload#38]
ERROR in build.bf062f81a70c821ad4dc.js from UglifyJs
SyntaxError: Unexpected token: name (last) [./~/vue-lazyload/vue-lazyload.es5.js:22,0]

vue-lazyload.es5.js:22,0：

 const debounce = function(action, idle) {
        **let last**
        return function() {
            let args = arguments
            clearTimeout(last)
            last = setTimeout(() => {
                action.apply(this, args)
            }, idle)
        }
    }

**Comment by hilongjw** [comment]
@GangRock 请升级到 0.7.5 版

**Comment by GangRock** [comment]
tks

Awe <notifications@github.com>于2016年9月14日周三 上午10:55写道：
