### ISSUE TITLE
Support custom container

### ISSUE THREAD

**Issue by matpaul** [hilongjw/vue-lazyload#4]
I have user list with avatars, but this list not in window so it will be cool if directive have option to provide custom container.

**Comment by hilongjw** [comment]
you need use it without vue ?

**Comment by matpaul** [comment]
@hilongjw i need use it with vue
i have list with v-for but it in div container with overflow:auto etc.. 
so scroll events not worked and checkCanShow calc for window not for container

**Comment by hilongjw** [comment]
OK, i got, I'll test it this weekend

**Comment by matpaul** [comment]
@hilongjw cool, thank you!

**Comment by hilongjw** [comment]
@matpaul finished
