### ISSUE TITLE
无法触发加载事件

### ISSUE THREAD

**Issue by g8up** [hilongjw/vue-lazyload#40]
vue-lazyload Version: 0.4.2
Demo：http://getcrx.cn
操作：
1. 打开页面，可以看到第一屏图标加载；
2. 在搜索框进行搜索，比如输入 `json`，搜索结果中的图标没能正常加载

搜索的实现方式：
```html
<div class="item" v-for="item in list | filterBy keyword in 'name' 'introduce' 'app_id' ">
    <img v-lazy="item.logo">
</div>
```

**Comment by hilongjw** [comment]
@g8up 升级到最新版试试

**Comment by g8up** [comment]
升级到 0.8.1 后，表现有提升。偶尔搜索出的结果没触发加载，滚动滚轮可触发（哪怕没有出现垂直滚动条）。
thx~

**Comment by isMyShell** [comment]
出现了同样的问题，最后如何解决，希望能得到帮助
