### ISSUE TITLE
懒加载没有效果

### ISSUE THREAD

**Issue by SquidwardTentacles** [hilongjw/vue-lazyload#407]
![image](https://user-images.githubusercontent.com/40991784/70678096-0326c500-1ccc-11ea-8cd6-fba06bb1580c.png)
![image](https://user-images.githubusercontent.com/40991784/70678114-16399500-1ccc-11ea-986c-0642d5b8732a.png)

**Comment by dota17** [comment]
After the webpack is packed, the image resource is renamed. You can use `require` to reference the image url.
```vue
data() {
    return {
      url: require('../assets/1.png'),
    }
  },
```
