### ISSUE TITLE
如果懒加载使用本地图片

### ISSUE THREAD

**Issue by 7demo** [hilongjw/vue-lazyload#41]
发现目前只能使用绝对路径的图片。

某些原因，需要懒加载的图片是本地的一些资源，通过相对路径的方式引入<code>./img/pic1.jpg</code>

这个可以实现吗

**Comment by hilongjw** [comment]
@7demo 你可以将本地图片放在web-dev-server 管理的静态目录里就可以访问了，比如 vue-cli 模板里的 dist/

**Comment by 7demo** [comment]
恩，那看来是在编译前，无法直接引入组件内部图片资源了。

如果能在组件中通过js引入本组件的图片资源并且发布出去就好了。

**Comment by x-cold** [comment]
这里其实可以通过使用 base64 来解决的，可能会造成包大小的一些增加，不过整体可用
