### ISSUE TITLE
img tag in lazy-compoent will not update when data change

### ISSUE THREAD

**Issue by peng** [hilongjw/vue-lazyload#412]
https://codesandbox.io/embed/loving-star-7knj0?fontsize=14&hidenavigation=1&theme=dark
In this example when change data, first img tag src attributes will not update.
In my project all img tag in lazy-component will not update when data change

**Comment by precogtyrant** [comment]
I have the same issue. Did you find a resolution?

**Comment by hilongjw** [comment]
@peng Hi, I updated this code example, you can take a look: [https://codesandbox.io/s/practical-banach-fgzgh](https://codesandbox.io/s/practical-banach-fgzgh)

The point is that you need to use the `:key="uniq"` with `lazy-component`

```html
// can't update
<div v-for="(item,index) in list" :key="index" >
      <lazy-component>
        <img  :src="item.src" :key="item.src" >
      </lazy-component>
    </div>
```

```html
// working fine now
<div v-for="(item,index) in list" :key="index" >
      <lazy-component :key="item.src" >
        <img  :src="item.src" :key="item.src" >
      </lazy-component>
    </div>
```

**Comment by peng** [comment]
@hilongjw  Oh it works. Good ! Thanks !
@precogtyrant  Auther answer the resolution !
