### ISSUE TITLE
Image doesnt load on reload

### ISSUE THREAD

**Issue by domideimel** [hilongjw/vue-lazyload#416]
When reloading the page at any position but the top the images in the viewport are not loading properly.
The lazystate says loaded, but the src attribute isn't set, so no image is shown.

![Bildschirmfoto 2020-02-10 um 09 36 07](https://user-images.githubusercontent.com/32941053/74133478-f1d53880-4be8-11ea-812f-dedf2d9c3b8b.png)

Here is my config:

```javascript
 Vue.use(VueLazyload, {
      attempt: 2,
      preLoad: 1.5,
      observer: true,
      loading: '/assets/images/product-detail-460x584.jpg'
    })
```

**Comment by littleCutePig** [comment]
楼主解决了吗
