### ISSUE TITLE
Vue3 Support

### ISSUE THREAD

**Issue by chenjiahan** [hilongjw/vue-lazyload#439]
Vue 3.0.0 has been officially released,, any plan to support Vue 3?

**Comment by peng** [comment]
@chenjiahan  We are working on it.

**Comment by chenjiahan** [comment]
Exciting!

**Comment by snowdream** [comment]
Is it ok now ?

**Comment by MDolega20** [comment]
> 
> 
> Is it ok now ?

Did you check this?

**Comment by chenjiahan** [comment]
@peng Hi, is there any progress?

**Comment by chenjiahan** [comment]
I forked `vue-lazyload` and added Vue 3 support.

Source Code: https://github.com/youzan/vant/tree/dev/packages/vant-lazyload
Document: https://youzan.github.io/vant/next/#/zh-CN/lazyload

**Comment by benjamin-t-frost** [comment]
I'm curious of the status of this ~
