### ISSUE TITLE
bug： 如果绑定的el不是window， 而是其它dom，在bind时，parentEl并没有在domcument中，这时就会有问题，图片始终Load不出来

### ISSUE THREAD

**Issue by ivan403704409** [hilongjw/vue-lazyload#46]
`<div class="pic" v-lazy:background-image.j-home-index="item"></div>`

`if (binding.modifiers) {
            parentEl = window.document.getElementById(Object.keys(binding.modifiers)[0])  //==> null
        }`

把 源 码 bind改成 inserted这样就正常了：
`if (isVueNext) {
        Vue.directive('lazy', {
            // bind: addListener,
            inserted: addListener,
            update: addListener,
            componentUpdated: lazyLoadHandler,
            unbind : componentWillUnmount
        })
    } `

**Comment by hilongjw** [comment]
added inserted hook
