### ISSUE TITLE
vue3分支引出报错

### ISSUE THREAD

**Issue by gao2009ss** [hilongjw/vue-lazyload#464]
@dota17
您的vue3分支
https://github.com/hilongjw/vue-lazyload/tree/next

引入vue-lazyload.js文件时浏览器报错Uncaught ReferenceError: process is not defined

**Comment by jambonn** [comment]
I forked vue-lazyload and added Vue 3 support.

Source Code: https://github.com/jambonn/vue-lazyload
npm package: https://www.npmjs.com/package/@jambonn/vue-lazyload
