### ISSUE TITLE
在 ie11 下报错  对象不支持 find 属性或方法

### ISSUE THREAD

**Issue by gggso** [hilongjw/vue-lazyload#48]
![286a521bf252750c7f00d8563782b422](https://cloud.githubusercontent.com/assets/6212790/19631656/ac2429ee-99d1-11e6-8f99-cf0c88560d9e.jpg)

![2ad8d82db389c20d0b827d6733083e31](https://cloud.githubusercontent.com/assets/6212790/19631699/0b9b3106-99d2-11e6-95c4-d1b51445b1e8.jpg)

**Comment by hilongjw** [comment]
@gggso 请升级到最新版本
