### ISSUE TITLE
请问一下，如果后端直接吐的 html 过来。如何实现懒加载图片。

### ISSUE THREAD

**Issue by zwlcoding** [hilongjw/vue-lazyload#49]
我把吐过来的 img 的 src 处理为 v-lazy 似乎并没有生效

**Comment by hilongjw** [comment]
@zwlcoding 是可以在后端渲染的且vue生效的范围的html标签中使用懒加载指令的。贴一下你的后端大概代码看一下

**Comment by zwlcoding** [comment]
后端没有做任何处理。就是简单的编辑器生成的 html 
用 ajax 获取过来之后，因为html里面的图片比较多，所以想做懒加载处理
按之前 jQuery 的写法可以前端处理好 html 代码段，填充到页面之后重新初始化图片懒加载就能实现，但是你这个没想到怎么用。。。

**Comment by hilongjw** [comment]
@zwlcoding  你是说的是页面渲染完成之后通过ajax 异步加载的html片段？因为使用 v-html 填进html片段不会调用vue解析，所以也没有使懒加载指令生效。解决方案我觉得可以试试 [调用vue的编译方法](http://vuejs.org/api/#Vue-compile)

**Comment by zwlcoding** [comment]
@hilongjw 还没升级到2.0+，看起来无解，或者只能用 jquery 插件再处理一下 - -

**Comment by aweiu** [comment]
@zwlcoding 其实就是起步教程中的示例就好了，别想复杂了
html:
```
<div id="target"></div>
```
js:
```
import Vue from 'vue'
new Vue({
  el: '#target',
  replace: false,
  template: 'ajax获取到的代码片段'
})
```

**Comment by zwlcoding** [comment]
@aweiu 之前的项目还没升级到 2.0 呢。。。。2.0 的应该没问题

**Comment by aweiu** [comment]
@zwlcoding 我上面提供的方法就是1.0的。

**Comment by zwlcoding** [comment]
@aweiu 还能这样用？有空试试。非常感谢

**Comment by Z-wave** [comment]
@zwlcoding 请问你解决了吗？

**Comment by expanding** [comment]
@aweiu 2.0的方法有没有

**Comment by biluochun** [comment]
template 的方法没分1.0 2.0，是vue的基础api文档。
可惜runtimeOnly模式下没template，哭。
