### ISSUE TITLE
最新版本`1.3.4`的产物中将const 编译了进去，会导致在ios9中执行报错

### ISSUE THREAD

**Issue by lsqy** [hilongjw/vue-lazyload#492]
![image](https://user-images.githubusercontent.com/18533232/175015392-27695aa7-59f4-4753-8e61-7a9dcca41711.png)

**Comment by lsqy** [comment]
![image](https://user-images.githubusercontent.com/18533232/175015709-f5b2fdf0-f354-479e-aab0-f3b5c750114a.png)

**Comment by jmx164491960** [comment]
我也遇到了。旧项目重新打包突然就报错了。。

**Comment by caozhong1996** [comment]
fixd #505
