### ISSUE TITLE
File size too large.

### ISSUE THREAD

**Issue by websanova** [hilongjw/vue-lazyload#52]
When using webpack this is adding 34kb too my app file (not minified). But considering it's only 206kb before and 242kb after this is still huge increase. Even minified it would be around 15kb. I guess from using the promise lib? Is it necessary to include all this extra baggage?

**Comment by hilongjw** [comment]
@websanova  I will provide a version without polyfill.

**Comment by websanova** [comment]
That would be great :-)

**Comment by hilongjw** [comment]
Hi, @websanova, I have removed the promise polyfill in the 0.9.0 version

**Comment by websanova** [comment]
Great, thx :-)
