### ISSUE TITLE
往前追加数据，list中图片状态不改变

### ISSUE THREAD

**Issue by gengfire** [hilongjw/vue-lazyload#53]
有一个list，下拉获取历史消息，需要将新数据插入到list前面，因为之前已经对list中图片作了处理，再次更新list数据，前面追加的图片显示的还是历史图片

**Comment by hilongjw** [comment]
@gengfire  请提供一下你的相关代码

**Comment by hilongjw** [comment]
you can see this [demo](http://hilongjw.github.io/vue-lazyload/) , it's work with list update fine 
[source code ](https://github.com/hilongjw/vue-lazyload-run)
