### ISSUE TITLE
使用了keep-alive 后 数据不会更新

### ISSUE THREAD

**Issue by wanwenjin** [hilongjw/vue-lazyload#54]
在使用了 keep-alive后 图片不会更新
![qq 20161109164854](https://cloud.githubusercontent.com/assets/5019921/20132171/9de9fb38-a69c-11e6-81a7-6a73b0c501d9.png)

**Comment by hilongjw** [comment]
建议参考 [http://vuejs.org/v2/guide/list.html#key](http://vuejs.org/v2/guide/list.html#key)

尝试使用 
```html
<div v-for="item in items" :key="item.id">
  <!-- content -->
</div>
```

**Comment by wanwenjin** [comment]
好像没有用
我的应用场景
有一个list页面
在点击其中一个item 进入详细画面，数据加载
退出再点击另一个item ，进入详细画面，数据加载
这个时候图片 还是第一个详细画面的图片，其实数据已经更新了

**Comment by wanwenjin** [comment]
应该是数据没有做绑定

**Comment by wanwenjin** [comment]
在重新进入后，原来的dom已经生成了 虽然数据更新了 但是没有做绑定 所以控件没有更新最新的数据

**Comment by hilongjw** [comment]
@wanwenjin 对于这个场景可能确实会存在这个问题，马上修复这里

**Comment by hilongjw** [comment]
问题还是在于Vue的更新机制， demo http://hilongjw.github.io/vue-lazyload/ 对于已有dom数据的更新运行正常。demo 源码 ： https://github.com/hilongjw/vue-lazyload-run
