### ISSUE TITLE
feature : events / methods on loaded/rendered

### ISSUE THREAD

**Issue by nusson** [hilongjw/vue-lazyload#59]
Can you please add some event or method to add some code once image is loaded/rendered

for exemple, I'd like to use an object-fit polyfill for ie :( (https://github.com/bfred-it/object-fit-images)
and I have to run objectFitImages(); once my img tag is rendered...

Exept this, your directive is awesome :)

**Comment by hilongjw** [comment]
@nusson  nice suggestion, I'll add the feature soon

**Comment by hilongjw** [comment]
@nusson it's done, you can update to `0.9.2` and try it

**Comment by nusson** [comment]
Thanks a lot :)
Works perfectly !
