### ISSUE TITLE
Use without webpack

### ISSUE THREAD

**Issue by sexysat** [hilongjw/vue-lazyload#61]
Is there anyway to use this without webpack (standalone in browser)

I tried including vue-lazyload-es5.js but Vue.lazyload is not defined

**Comment by sexysat** [comment]
Edit just read the code and found out you have to call window.install(Vue) before usage

**Comment by tpalmer75** [comment]
Can you elaborate on how you solved this?

Browser says `window.install is not a function`. Otherwise it says `Uncaught ReferenceError: VueLazyLoad is not defined`
