### ISSUE TITLE
在微信 WebView 中使用时 img 的背景先是会显示黑色

### ISSUE THREAD

**Issue by wangxiao** [hilongjw/vue-lazyload#63]
滚动到未加载图片的 img 处，图片背景会显示为黑色，然后再加载图片。仅在微信的 WebView 中发现有这个问题，其余浏览器环境均正常。试过 !important 之类的方式设置 background-color，问题仍然存在。

模板中的使用方式：
```
<img v-lazy="photoUrl">
```

**Comment by hilongjw** [comment]
@wangxiao 是使用的自定义loading 图片还是默认的？

**Comment by wangxiao** [comment]
默认的情况

**Comment by hilongjw** [comment]
@wangxiao 应该是默认填充的base64 data url 编码在微信的问题，可以通过配置loading 图片解决。我之后会测试更新一个新的占位data url

**Comment by wangxiao** [comment]
恩，好的，目前对我的业务影响不大。

**Comment by hilongjw** [comment]
@wangxiao 在 `0.9.3` 中换了一个 data url image, 可以测试一下看是否有问题
