### ISSUE TITLE
vue SPA 中引入 vue-lazyload 会在QQ系列内核无法访问！

### ISSUE THREAD

**Issue by JaneCC** [hilongjw/vue-lazyload#64]
vue SPA 中引入 vue-lazyload 会在QQ系列内核.UC系列内核，原生chrome无影响无法访问！

**Comment by hilongjw** [comment]
请提供一下相关的报错， 是用的最新的0.9.2 版本吗？

**Comment by JaneCC** [comment]
vue 1  SPA 中 引入会存在，vue2 SPA 中不存在这个情况

**Comment by hilongjw** [comment]
@JaneCC 可能是之前是用了ES6 Array.find 没有使用 polyfill 导致的，请升级到目前最新版本吧
