### ISSUE TITLE
源码中出现的scale是什么意思

### ISSUE THREAD

**Issue by mengchen129** [hilongjw/vue-lazyload#70]
我在源码中发现了以下代码：
`scale: Options.scale || inBrowser ? window.devicePixelRatio : 1`
貌似觉得这个地方可能是要根据设备像素比加载高清图之类的，但发现实际并没有用。请问这个是否是将来要增加的功能么。我正好需要这么一个功能，请问该如何做呢。

**Comment by hilongjw** [comment]
@mengchen129 是的，这是 todo 了很久的一个想做的一个 feature。

**Comment by mengchen129** [comment]
今天搞了一下把vue-lazyload和retina集成在一起，详见 [vue-lazyload-retina](https://github.com/mengchen129/vue-lazyload-retina)  。希望retina这个功能可以集成到lazyload里哈

**Comment by hilongjw** [comment]
@mengchen129 👍，我会参考这里来实现
