### ISSUE TITLE
在安卓设备下，el.setAttribute('src', src) 这么设置src会导致layout，layout后scroll事件会被循环调用

### ISSUE THREAD

**Issue by zyip** [hilongjw/vue-lazyload#72]
const setElRender = (el, bindType, src, state, context) => {
        if (!bindType) {
            //el.setAttribute('src', src) 
            if(el.getAttribute('src')!=src){
                el.setAttribute('src', src)
            }
        } else {
            el.style[bindType] = 'url(' + src + ')'
        }
        el.setAttribute('lazy', state)
        if (context) {
            $Lazyload.$emit(state, context)
        }
    }

**Comment by hilongjw** [comment]
@zyip  fix in [](https://github.com/hilongjw/vue-lazyload/commit/d39c28eb1f88fad798244e1a98ce252bd106b757)
