### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by madgecool** [hilongjw/vue-lazyload#75]
您好，我有一些问题请教一下
第一个问题，需要有滚动这些操作才加载，在移动端，如果页面就只有一页，那么直接就显示lazy="error",
第二问题，为什么会重复加载，滚动到那位置，图像已经报错了显示的是lazy="error",然后向下滚动，再向上滚动到原位置，显示的是lazy="load"，设置了attempt:2.
第三个问题：不能再用vue过滤器吗？

**Comment by hilongjw** [comment]
问题1 能提供一个简单的在线demo吗；attempt 是加载失败的尝试次数限制，有可能会有因为网络问题在首次加载不成功, 问题 3 应该是vue不支持在指令中使用过滤器,可以使用methods代替
