### ISSUE TITLE
关于添加overflow: scroll图片加载失败问题

### ISSUE THREAD

**Issue by tytydas** [hilongjw/vue-lazyload#76]
示例中UL元素添加一个固定高度和overflow: scroll，图片只会第一次加载到第一次看到的区域，后面不会进行加载，但是滚动就能触发加载，后来在opstion中添加listenEvents为touchmove，尚未能触发事件，求解决
`<ul class="page-lazyload-list" style="height:500px;overflow:scroll">
      <li class="page-lazyload-listitem" v-for="item in list">
        < img v-lazy="item" class="page-lazyload-image">
      </li>
    </ul>`

**Comment by hilongjw** [comment]
```
<ul id="container">
  <li v-for="img in list">
    <div v-lazy:background-image.container="img"></div>
  </li> 
</ul>
```
#33

**Comment by isMyShell** [comment]
出现了一样的问题 ，最后怎么解决掉的，求帮助
