### ISSUE TITLE
如果页面内有多个父容器元素并且可能会在将来出现，如何设置呢？

### ISSUE THREAD

**Issue by mengchen129** [hilongjw/vue-lazyload#77]
我有一个单页应用，使用的vue-router管理的路由，其中有两个路由内都使用了元素内滚动。那么对于这种情况，应该如何配置呢？
v-lazy.container 只能设置一个父元素，如果有多个父元素如何设置。而且如果container在另一个路由内，这样页面加载时container元素并没有创建，即使后来切换到该路由，也不会生效。

**Comment by hilongjw** [comment]
@mengchen129 lazyload 指令生效的同时是一定已经存在它们的父元素了，应该不会有这个问题
