### ISSUE TITLE
V-Lazy Load Error

### ISSUE THREAD

**Issue by pandubaraja** [hilongjw/vue-lazyload#79]
V-Lazy load error after switching page with different image url

`<img v-lazy="'http://localhost/static/img/vendors/'+ vendor.vendor_name +'/thumbnail/' + i.name" class="img-fluid" style="border: 1px solid #ccc;">`

First load attempt success

`<img data-v-3deeb98e="" class="img-fluid" src="http://localhost/static/img/vendors/testing/thumbnail/1481287382-Screen Shot 2016-12-09 at 7.40.58 PM.png" lazy="loaded" style="border: 1px solid rgb(204, 204, 204);">`

Second load attempt with different url return v-lazy error

`<img data-v-3deeb98e="" class="img-fluid" src="dist/static/default.jpg" lazy="error" style="border: 1px solid rgb(204, 204, 204);">`

I need to refresh the whole page to make it work again

Thank you

**Comment by hilongjw** [comment]
@pandubaraja I'm not sure what the problem is, try using the newer version
