### ISSUE TITLE
对v-html的dom 不支持呢

### ISSUE THREAD

**Issue by yu530feng** [hilongjw/vue-lazyload#94]
因为业务是文本编辑器，图文结合的dom片断，用v-html载入，但不支持

**Comment by hilongjw** [comment]
@yu530feng v-html 内的元素是不会获得vue指令解析的，所以是不支持的。

**Comment by Z-wave** [comment]
@hilongjw 但是在实际开发中，这种业务场景是很常见的！

**Comment by ansonhorse** [comment]
也在纠结这个问题，请问有新进展么？

**Comment by biluochun** [comment]
#257

**Comment by ansonhorse** [comment]
@biluochun 谢谢，使用这种方式确实是可以运行了。
不过奇怪的是，图片是全部一起被加载了。
```html
<div v-lazy-container="{ selector: 'img', loading: 'https://dummyimage.com/600x400/000/fff' }">
  <div class="item-desc" v-html="desc"></div>
 </div>
<!-- desc里面基本上都是img：<img data-src="xxx" /> -->
```
页面载入后，这个div是在可视范围内的，然后全部图片就一起加载了，如果把这个div放到页面加载完成后看不到的地方，这时候是正常的。
请问是我哪里没有设置好么？请指点，谢谢！
