### ISSUE TITLE
how to force 'pass by' images load?

### ISSUE THREAD

**Issue by fishenal** [hilongjw/vue-lazyload#96]
i got a situation on mobile pages.
if scroll too fast,  it will ignore some images to load, and the calculation of images heights got wrong, make a gap of two cols images.

Is there anyway to force the pass by images loading?

**Comment by hilongjw** [comment]
@fishenal  you can invoke `this.$Lazyload.lazyLoadHandler()` to make it update

**Comment by camslice** [comment]
If the user has not yet scrolled down the page, is it possible to use `this.$Lazyload.lazyLoadHandler()` to trigger all images to start loading? Doesn't seem to work for me.
